name: Link Check & Deploy

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 9 * * 1"  # Mondays 09:00 UTC
  workflow_dispatch:

permissions:
  contents: write   # commit updated assets/health.json
  pages: write      # deploy to GitHub Pages
  id-token: write   # required by actions/deploy-pages

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run link checker
        run: node scripts/check_links.mjs

      - name: Commit updated health.json (if changed)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update link health"
          file_pattern: assets/health.json

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
